version: '3.9'

services:
  front:
    build: 
      context: task-manager
    restart: always
    image: task-manager-last:1.0
    expose:
     - 80
    ports:
     - 8089:80
    environment:
      - BACKEND_host=localhost
      - BACKEND_PORT=8080
    depends_on:
      - backend
  java_app:
    container_name: java_app
    image: pee-java-app:1.0.0
    build: -
    ports:
          - 8080:8080
    environment:
      - DATABASE_URL = jdbc:postgresql://localhost:5432/task_manager
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_DB = postgres

    




